$(function(){
    $('#james').click(function(){
        $('#modal').modal('show')
        .find('#modalContent')
        .load($(this).attr('value'))
    });
    $('#printModal').click(function(){
        $('#model').modal('show')
            .find('#modelContent')
            .load($(this).attr('value'));
    });
});